<?php

namespace AppBundle\Repository;

/**
 * BoardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $user
     * @param $board
     * @return array
     */
    public function check($user, $board)
    {
        return $this
            ->createQueryBuilder('board')
            ->join('board.user', 'user')
            ->where("user.nickname LIKE :us")
            ->andWhere("board.id != :bo")
            ->setParameter('us', '%'.$user.'%')
            ->setParameter('bo', $board)
            ->getQuery()
            ->getResult()
            ;
    }
}
