<?php

namespace AppBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $stick
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getPosition($stick)
    {
        return $this
            ->createQueryBuilder('item')
            ->andWhere('item.stick = :stick')
            ->setParameter('stick', $stick)
            ->select('COUNT(item.id)')
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
