<?php

namespace AppBundle\Repository;

/**
 * StickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StickRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $board
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getPosition($board)
    {
        return $this
            ->createQueryBuilder('stick')
            ->andWhere('stick.board = :board')
            ->setParameter('board', $board)
            ->select('COUNT(stick.id)')
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
