<?php

namespace AppBundle\Repository;

/**
 * StickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StickRepository extends \Doctrine\ORM\EntityRepository
{
}
