<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $text
     * @param string $board
     * @return array
     */
    public function getUserByNickname($text, $board)
    {
        return $this
            ->createQueryBuilder('user')
//            ->join('user.boards', 'boards')
            ->andWhere("user.nickname LIKE :nick")
//            ->andWhere('boards.id != :board')
            ->setParameter('nick', '%'.$text.'%')
//            ->setParameter('board', $board)
            ->getQuery()
            ->getResult()
            ;
    }
}
