<?php

namespace AppBundle\Repository;
use Doctrine\Common\Collections\Criteria;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $text
     * @return array
     */
    public function getUserByNickname($text)
    {
        return $this
            ->createQueryBuilder('user')
            ->where("user.nickname LIKE :nick")
            ->setParameter('nick', '%'.$text.'%')
            ->getQuery()
            ->getResult()
            ;
    }
}
