<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $text
     * @param int $boardId
     * @return array
     */
    public function getUserByNickname($text, $boardId)
    {
        return $this
            ->createQueryBuilder('user')
            ->join('user.boards', 'boards')
            ->where("user.nickname LIKE :nick")
            ->andWhere('user.boards != :board')
            ->setParameter('board', $boardId)
            ->setParameter('nick', '%'.$text.'%')
            ->getQuery()
            ->getResult()
            ;
    }
}
